"use client";

import { useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { useTenant } from "@/lib/tenant-context";
import { createClient } from "@/lib/supabase/client";
import { sectionHeadingClass } from "@/lib/design-system";

export default function ReportsSettingsPage() {
    const tenant = useTenant();
    const router = useRouter();
    const [saving, setSaving] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [reportCoverUrl, setReportCoverUrl] = useState(tenant.report_cover_url || "");
    const coverInputRef = useRef<HTMLInputElement>(null);

    const handleSave = async () => {
        setSaving(true);
        try {
            const res = await fetch("/api/tenant", {
                method: "PATCH",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    report_cover_url: reportCoverUrl || null,
                }),
            });
            if (!res.ok) throw new Error();
            toast.success("Report cover saved");
            // Re-render the server layout so the TenantProvider gets the new
            // report_cover_url — otherwise the PDF generator still sees stale data.
            router.refresh();
        } catch {
            toast.error("Failed to save");
        } finally {
            setSaving(false);
        }
    };

    const handleReportCoverUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        if (file.size > 10 * 1024 * 1024) {
            toast.error("Report cover must be under 10MB");
            return;
        }

        if (file.type !== "application/pdf") {
            toast.error("Only PDF files are supported for report covers");
            return;
        }

        setUploading(true);
        try {
            const supabase = createClient();
            const path = `${tenant.id}/report-cover.pdf`;

            const { error } = await supabase.storage
                .from("tenant-assets")
                .upload(path, file, { upsert: true, contentType: "application/pdf" });

            if (error) throw error;

            const { data: urlData } = supabase.storage
                .from("tenant-assets")
                .getPublicUrl(path);

            // Bust CDN cache so a re-uploaded cover shows immediately.
            setReportCoverUrl(`${urlData.publicUrl}?v=${Date.now()}`);
            toast.success("Report cover uploaded");
        } catch (err) {
            console.error("Report cover upload failed", err);
            const msg = err instanceof Error ? err.message : "Unknown error";
            toast.error(`Failed to upload report cover: ${msg}`);
        } finally {
            setUploading(false);
        }
    };

    return (
        <div className="space-y-8">
            <div>
                <h2 className={sectionHeadingClass}>Report Cover Page</h2>
                <p className="text-sm text-muted-foreground mt-1">
                    Appended as the front page of every PDF report generated by your tenant.
                </p>
            </div>

            <div>
                <label className="block text-sm font-medium mb-2">Cover File</label>
                <div className="flex items-start gap-4">
                    {reportCoverUrl ? (
                        <a
                            href={reportCoverUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            title="Click to preview full-size"
                            className="w-32 h-44 rounded-xl border border-border bg-muted/30 overflow-hidden block group"
                        >
                            {/* Inline PDF thumbnail — clicking the link opens the full preview.
                                pointer-events-none lets the parent <a> catch clicks. */}
                            <iframe
                                src={`${reportCoverUrl}#toolbar=0&navpanes=0&scrollbar=0&view=Fit`}
                                className="w-full h-full pointer-events-none"
                                title="Report cover preview"
                            />
                        </a>
                    ) : (
                        <div className="w-32 h-44 rounded-xl border-2 border-dashed border-border flex items-center justify-center bg-muted/20 text-center p-3">
                            <span className="text-xs text-muted-foreground leading-snug">
                                No cover — a default one is generated
                            </span>
                        </div>
                    )}
                    <div className="space-y-2 flex-1">
                        <button
                            onClick={() => coverInputRef.current?.click()}
                            disabled={uploading}
                            className="px-4 py-2 text-sm font-medium border border-border rounded-xl hover:bg-muted/50 transition-colors"
                        >
                            {uploading ? "Uploading..." : "Upload Report Cover"}
                        </button>
                        {reportCoverUrl && (
                            <button
                                onClick={() => setReportCoverUrl("")}
                                className="block text-xs text-destructive hover:underline"
                            >
                                Remove cover
                            </button>
                        )}
                        <p className="text-xs text-muted-foreground">
                            PDF only — all pages are prepended to every report. Portrait A4 sizing
                            is ideal. Max 10MB. Leave empty to auto-generate a cover with your logo
                            and the report details.
                        </p>
                    </div>
                    <input
                        ref={coverInputRef}
                        type="file"
                        accept="application/pdf"
                        onChange={handleReportCoverUpload}
                        className="hidden"
                    />
                </div>
            </div>

            {/* Save */}
            <div className="pt-4 border-t border-border">
                <button
                    onClick={handleSave}
                    disabled={saving}
                    className="px-6 py-2.5 bg-foreground text-background font-medium text-sm rounded-lg hover:bg-foreground/90 transition-colors disabled:opacity-50"
                >
                    {saving ? "Saving..." : "Save Changes"}
                </button>
            </div>
        </div>
    );
}
