-- 038_activity_audit_summarize_jsonb.sql
-- Adds optional TG_ARGV[1]: comma-separated field names whose UPDATE diffs
-- collapse to a fixed sentinel instead of dumping the full before/after JSONB.
-- Motivation: reports.data holds the entire form payload, so the row-level diff
-- generated by 019 produces an unreadable wall of JSON in the activity feed.

CREATE OR REPLACE FUNCTION log_activity_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_entity_type text := TG_ARGV[0];
    v_summary_fields text[] := CASE
        WHEN TG_NARGS >= 2 AND TG_ARGV[1] IS NOT NULL AND TG_ARGV[1] <> ''
        THEN string_to_array(TG_ARGV[1], ',')
        ELSE ARRAY[]::text[]
    END;
    v_entity_id uuid;
    v_tenant_id uuid;
    v_action text;
    v_changes jsonb := '{}'::jsonb;
    v_field text;
    v_old_val jsonb;
    v_new_val jsonb;
    v_old_jsonb jsonb;
    v_new_jsonb jsonb;
    v_ignored text[] := ARRAY['id','created_at','updated_at','tenant_id','created_by'];
BEGIN
    IF current_setting('audit.skip', true) = 'on' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_action := 'created';
        v_entity_id := (NEW.id)::uuid;
        v_tenant_id := (NEW.tenant_id)::uuid;
        v_changes := NULL;

    ELSIF TG_OP = 'UPDATE' THEN
        v_action := 'updated';
        v_entity_id := (NEW.id)::uuid;
        v_tenant_id := (NEW.tenant_id)::uuid;
        v_old_jsonb := to_jsonb(OLD);
        v_new_jsonb := to_jsonb(NEW);

        FOR v_field, v_new_val IN SELECT * FROM jsonb_each(v_new_jsonb)
        LOOP
            IF v_field = ANY(v_ignored) THEN CONTINUE; END IF;
            v_old_val := v_old_jsonb -> v_field;
            IF v_old_val IS DISTINCT FROM v_new_val THEN
                IF v_field = ANY(v_summary_fields) THEN
                    v_changes := v_changes || jsonb_build_object(
                        v_field,
                        jsonb_build_object('old', NULL, 'new', to_jsonb('updated'::text))
                    );
                ELSE
                    v_changes := v_changes || jsonb_build_object(
                        v_field,
                        jsonb_build_object('old', v_old_val, 'new', v_new_val)
                    );
                END IF;
            END IF;
        END LOOP;

        IF v_changes = '{}'::jsonb THEN RETURN NEW; END IF;

    ELSIF TG_OP = 'DELETE' THEN
        v_action := 'deleted';
        v_entity_id := (OLD.id)::uuid;
        v_tenant_id := (OLD.tenant_id)::uuid;
        v_old_jsonb := to_jsonb(OLD);

        FOR v_field, v_old_val IN SELECT * FROM jsonb_each(v_old_jsonb)
        LOOP
            IF v_field = ANY(v_ignored) THEN CONTINUE; END IF;
            v_changes := v_changes || jsonb_build_object(
                v_field,
                jsonb_build_object('old', v_old_val, 'new', NULL)
            );
        END LOOP;
    END IF;

    INSERT INTO activity_logs (entity_type, entity_id, action, changes, performed_by, tenant_id)
    VALUES (v_entity_type, v_entity_id, v_action, v_changes, auth.uid(), v_tenant_id);

    RETURN COALESCE(NEW, OLD);
END;
$$;

COMMENT ON FUNCTION log_activity_change() IS
  'Generic audit trigger. TG_ARGV[0]=entity_type. Optional TG_ARGV[1]=comma-separated field names to summarize instead of diff. Set audit.skip=on to bypass.';

DROP TRIGGER IF EXISTS audit_reports ON public.reports;
CREATE TRIGGER audit_reports
AFTER INSERT OR UPDATE OR DELETE ON public.reports
FOR EACH ROW EXECUTE FUNCTION log_activity_change('report', 'data');
